### ISSUE TITLE
binutils-2.25: `require': nokogiri.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by infoman** [rubys/nokogumbo#25] opened 2015-06-07 06:41 UTC
Projects using Bundler and Nokogumbo fail to load if built using binutils-2.25. The following error message appears:

```
/home/infoman/work/dev/binutils-bisect/bundler-test/vendor/bundle/ruby/2.0.0/gems/nokogumbo-1.4.2/lib/nokogumbo.rb:2:in `require': nokogiri.so: cannot open shared object file: No such file or directory - /home/infoman/work/dev/binutils-bisect/bundler-test/vendor/bundle/ruby/2.0.0/extensions/x86-linux/2.0.0/nokogumbo-1.4.2/nokogumboc.so (LoadError)
```

binutils bug report was closed as invalid: https://sourceware.org/bugzilla/show_bug.cgi?id=18448

**Comment by rubys** [comment] 2015-06-07 22:16
First, good detective work!

Unfortunately, it isn't clear to me (yet) what changes would be needed to nokogumbo.

At least on my system (Ubuntu 14.04), I don't see any direct calls to binutils anywhere.  I presume that gcc is calling ld.  The call to gcc is made by the generated Makefile.  The Makefile is generated by extconf.rb.

Perhaps if somebody knowledgeable on binutils could suggest how the generated Makefile should be changed, I could work backwards from there to see how to modify extconf.rb to get the correct Makefile produced?

**Comment by svoop** [comment] 2015-11-15 09:56
Wow, nice job tracking this down to binutils, @infoman!

This could become a major show stopper for quite a few people since the Sanitize gem has switched to Nokogumbo; and unless this is fixed, deployments e.g. to Gentoo servers are broken.

There's a Gentoo ebuild (package) for Nokogumbo, maybe you see something helpful there:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-ruby/nokogumbo/nokogumbo-1.4.2.ebuild

Otherwise, I suggest you (@rubys) ask for help on Stackoverflow. I could do it for you and relay the anwers here, but it's maybe better if you as the author ask directly. In any case, thanks a lot for Nokogumbo! I would love to roll it to our box.

**Comment by svoop** [comment] 2015-11-15 10:21
Not sure whether this is related, but building Nokogumbo on OS X fails if the "gumbo-parser" brew is installed:

> nokogumbo.c:160:12: error: use of undeclared identifier 'GUMBO_NODE_TEMPLATE'; did you mean 'GUMBO_TAG_TEMPLATE'?
      case GUMBO_NODE_TEMPLATE:
           ^~~~~~~~~~~~~~~~~~~
           GUMBO_TAG_TEMPLATE

**Comment by svoop** [comment] 2015-11-15 11:58
The GUMBO_TAG_TEMPLATE error is unrelated. Homebrew is still on gumbo-parser 0.9.3 which is not compatible with current Nokogumbo. I've just submitted a PR to lift homebrew to 0.10.1 which works fine.

**Comment by rubys** [comment] 2015-11-15 14:23
> There's a Gentoo ebuild (package) for Nokogumbo, maybe you see something helpful there

Looks like it is coping the generated shared object to the lib directory; and given that the problem is that binutils can't find the shared object, that could indeed be a fix.  Unfortunately, I'm not in a position to try it myself -- all I can say is that that change doesn't break anything for me.

@svoop: can you try it?

Here's the proposed change:

https://github.com/rubys/nokogumbo/commit/19b25fe09da4ddb3d9b89a4b44dba48303143313

You can pull it down using the copy-to-lib branch:

https://github.com/rubys/nokogumbo/tree/copy-to-lib

**Comment by svoop** [comment] 2015-11-15 22:14
@rubys I've tried to test it, but I can't find a way to. My app is using the sanitize gem and pulls nokogumbo as a runtime dependency. I've tried to add nokogumbo (from Github) to the Gemfile explicitly, but it didn't work (I guess because there's no .gemspec in the repo). Next I built the gem locally and tried to install it on the server manually with `bundle exec gem install`. This fails as well, apparently Bundler uninstalls first and then trips over the incomplete bundle. I'm running out of ideas, do you have one?

**Comment by svoop** [comment] 2015-11-16 10:52
@rubys Some more details about my testing attempts:

Adding `gem 'nokogumbo', github: 'rubys/nokogumbo', branch: 'copy-to-lib'` to the Gemfile results in:

    Could not find gem 'nokogumbo (>= 0) ruby' in
    git://github.com/rubys/nokogumbo.git (at copy-to-lib).
    Source does not contain any versions of 'nokogumbo (>= 0) ruby

I've then forked nokogumbo and added a gemspec based on the metadata of the built gem. Honestly, I'm not familiar at all with non-Ruby gems, so I don't know whether this is bound to fail. In any case, I can then `bundle install`, but the install is broken and errors both locally as well as when deploying:

    /Users/development/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- nokogumboc (LoadError)
    	from /Users/development/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    	from /Users/development/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    	from /Users/development/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    	from /Users/development/.gem/ruby/2.2.3/bundler/gems/nokogumbo-90b1b99b20f2/lib/nokogumbo.rb:2:in `<top (required)>'
    	from /Users/development/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
    	from /Users/development/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    	from /Users/development/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
    	from /Users/development/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
    	from /Users/development/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
    	from /Users/development/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
    	from /Users/development/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
    	from /Users/development/Development/wemakeit/config/application.rb:7:in `<top (required)>'
    	from /Users/development/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:141:in `require'
    	from /Users/development/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
    	from /Users/development/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:67:in `console'
    	from /Users/development/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    	from /Users/development/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
    	from bin/rails:4:in `require'
    	from bin/rails:4:in `<main>'

But this could really just be normal when adding gemspec to a non-Ruby gem. Here's my fork if you'd like to see what exactly I put there:

https://github.com/svoop/nokogumbo/tree/copy-to-lib

End of the road for me unless you have another idea :disappointed:

**Comment by svoop** [comment] 2015-11-16 11:59
I've tried a couple more things such as adding the gem version explicitly which apparently is necessary for gems without gemspecs pulled from repos:

    gem 'nokogumbo', '1.4.5', github: 'rubys/nokogumbo', branch: 'copy-to-lib'

While `bundle install` works, I can't do e.g. `rails c`. I always hit the `cannot load such file -- nokogumboc (LoadError)` mentioned in my previous comment.

**Comment by rubys** [comment] 2015-11-17 01:34
OK, I've pushed out a new gem.

**Comment by svoop** [comment] 2015-11-17 08:29
Bummer. I can't deploy without hitting the dreaded LoadError, but I can install the bundle manually with exactly the same user and command. Apparently, the environment is different during the Capistrano deploy. I'll have to dig deeper.

@infoman What's your mileage with nokogumbo-1.4.6?

**Comment by MaximeD** [comment] 2015-12-14 14:39
I had the same problem with a gentoo. Turns out that https://github.com/rubys/nokogumbo/pull/8/files was guilty, temporary renaming file `/etc/gentoo-release` and reinstalling `nokogumbo` fixed the issue.

**Comment by svoop** [comment] 2015-12-18 19:25
@MaximeD Thanks a bunch for the hint! I've just reverted the two Gentoo workaround commits and [created a pull request](/rubys/nokogumbo/pull/38).

**Comment by svoop** [comment] 2015-12-18 20:44
Guess we can close this one now.

**Comment by infoman** [comment] 2015-12-23 15:42
Another error now in 2.4.7:

```
linking shared-object nokogumboc.so                                                                                                                                                                                  
nokogumbo.o: In function `parse':                                                                                                                                                                                    
nokogumbo.c:(.text+0x3ef): undefined reference to `Nokogiri_wrap_xml_document'
```

**Comment by infoman** [comment] 2015-12-23 15:45
full log: http://pastebin.com/4Vu8bjxc

**Comment by kakra** [comment] 2016-02-28 08:06
This was fixed for me after upgrading sanitize, nokogiri and nokogumbo in the bundle.

**Comment by gkellogg** [comment] 2017-06-01 23:59
FWIW, I'm seeing this with http://github.com/ruby-rdf/rdf-distiller when deploying on Heroku. Works fine when installed on macOS.

```
LoadError: /tmp/build_4ce7148706c7956c5030dc8773cdcd5d/gkellogg-rdf-distiller-5514a09/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.7.2/ext/nokogiri/nokogiri.so: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.4.0/gems/nokogumbo-1.4.12/lib/nokogumboc.so
	from /app/vendor/bundle/ruby/2.4.0/gems/nokogumbo-1.4.12/lib/nokogumbo.rb:2:in `require'
	from /app/vendor/bundle/ruby/2.4.0/gems/nokogumbo-1.4.12/lib/nokogumbo.rb:2:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/console.rb:18:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:362:in `console'
        ...
```

binutils is not involved. Ruby version 2.4.1. Gems included by the bundle:
  * addressable (2.5.1)
  * bcp47 (0.3.3)
  * better_errors (2.1.1)
  * binding_of_caller (0.7.2)
  * builder (3.2.3)
  * bundler (1.14.6)
  * byebug (9.0.6)
  * coderay (1.1.1)
  * concurrent-ruby (1.0.5)
  * connection_pool (2.2.1)
  * crack (0.4.3)
  * data_objects (0.10.17)
  * debug_inspector (0.0.3)
  * diff-lcs (1.3)
  * domain_name (0.5.20170404)
  * ebnf (1.1.0)
  * equivalent-xml (0.6.0)
  * erubis (2.7.0)
  * foreman (0.84.0)
  * haml (5.0.1)
  * hamster (3.0.0)
  * hashdiff (0.3.4)
  * htmlentities (4.3.4)
  * http-cookie (1.0.3)
  * i18n (0.8.4)
  * jsmin (1.0.1)
  * json-compare (0.1.8)
  * json-ld (2.1.3 18707be)
  * json-ld-preloaded (1.1.0 7c386a1)
  * jsonpath (0.8.3)
  * ld-patch (0.3.1 ba39e89)
  * link_header (0.0.8)
  * linkeddata (2.2.0 910059f)
  * maruku (0.7.3)
  * mime-types (2.99.3)
  * mini_portile2 (2.1.0)
  * multi_json (1.12.1)
  * net-http-persistent (3.0.0)
  * netrc (0.11.0)
  * nokogiri (1.7.2)
  * nokogumbo (1.4.12)
  * public_suffix (2.0.5)
  * puma (3.9.0)
  * rack (1.6.8)
  * rack-cache (1.7.0)
  * rack-linkeddata (2.0.0 0969620)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rake (12.0.0)
  * rdf (2.2.6 a4dcf9a)
  * rdf-aggregate-repo (2.2.0 45fafd5)
  * rdf-distiller (2.2.5)
  * rdf-do (2.0.0 790ef09)
  * rdf-isomorphic (2.0.0 31aacaf)
  * rdf-json (2.0.0 676c0e7)
  * rdf-microdata (2.2.1 73793da)
  * rdf-n3 (2.1.0 07f88ea)
  * rdf-rdfa (2.2.2 868a0f9)
  * rdf-rdfxml (2.0.0 038a5a4)
  * rdf-reasoner (0.4.2 b9fb806)
  * rdf-spec (2.2.0 dd36d57)
  * rdf-tabular (2.2.0 b31b66e)
  * rdf-trig (2.0.0 b35a061)
  * rdf-trix (2.0.0 86d325d)
  * rdf-turtle (2.2.0 71bf758)
  * rdf-vocab (2.2.2 5225a6e)
  * rdf-xsd (2.1.0 6946d6d)
  * redcarpet (3.4.0)
  * rest-client (1.8.0)
  * rest-client-components (1.4.0)
  * rspec (3.6.0)
  * rspec-core (3.6.0)
  * rspec-expectations (3.6.0)
  * rspec-its (1.2.0)
  * rspec-mocks (3.6.0)
  * rspec-support (3.6.0)
  * safe_yaml (1.0.4)
  * shotgun (0.9.2)
  * sinatra (1.4.8)
  * sinatra-assetpack (0.3.5)
  * sinatra-linkeddata (2.0.0 a5aca0a)
  * sparql (2.2.0 91808cc)
  * sparql-client (2.1.0 546482a)
  * sxp (1.0.0 e382c65)
  * syntax (1.2.1)
  * temple (0.8.0)
  * thor (0.19.4)
  * tilt (1.4.1)
  * unf (0.1.4)
  * unf_ext (0.0.7.4)
  * webmock (2.3.2)
  * yard (0.9.9)

**Comment by glebm** [comment] 2017-06-02 04:07
Downgrading to nokogumbo 1.4.11 fixes Heroku deployment, so definitely something is up.
The issue appears on both cedar-14 (Ubuntu 14 LTS) and heroku-16 (Ubuntu 16 LTS) stacks.

**Comment by gkellogg** [comment] 2017-06-02 17:07
Thanks @glebm, that did the trick!

**Comment by kinyodan** [comment] 2017-06-03 13:35
please help out of nowhere i cant deploy to app to heroku i get error below cant figure out why 

`remote:        Removing aws-sdk-resources (2.9.27)
remote:        Removing aws-sdk-core (2.9.27)
remote:        Removing pubnub (4.0.21)
remote:        Removing aws-sdk (2.9.27)
remote: -----> Installing node-v6.10.0-linux-x64
remote: -----> Detecting rake tasks
remote: sh: 2: Syntax error: Unterminated quoted string
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: /tmp/build_76777b11543bb95aa369c0e3a4e5a0ed/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.2/ext/nokogiri/nokogiri.so: cannot open shared object file: No such file or directory - /tmp/build_c179659165820243e28ab4170607d06b/vendor/bundle/ruby/2.3.0/gems/nokogumbo-1.4.12/lib/nokogumboc.so
remote:  !     /tmp/build_c179659165820243e28ab4170607d06b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'`

**Comment by kinyodan** [comment] 2017-06-03 13:38
`remote: -----> Detecting rake tasks
remote: sh: 2: Syntax error: Unterminated quoted string
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: /tmp/build_76777b11543bb95aa369c0e3a4e5a0ed/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.7.2/ext/nokogiri/nokogiri.so: cannot open shared object file: No such file or directory - /tmp/build_c179659165820243e28ab4170607d06b/vendor/bundle/ruby/2.3.0/gems/nokogumbo-1.4.12/lib/nokogumboc.so
remote:  !     /tmp/build_c179659165820243e28ab4170607d06b/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'`

**Comment by glebm** [comment] 2017-06-03 14:08
@kinyodan Put this in your gemfile for now:

```ruby
# Fix version until https://github.com/rubys/nokogumbo/issues/25 gets fixed
gem 'nokogumbo', '= 1.4.11'
```

**Comment by kinyodan** [comment] 2017-06-05 23:52
@glebm  thank you! thank you! thank you !
worked like a charrm .

**Comment by tbhockey** [comment] 2017-06-29 19:46
For me I had little choice but to run `bundle update nokogumbo`, bringing me to 1.4.13, which thankfully did the trick for me.

**Comment by stevecheckoway** [comment] 2018-08-25 22:29
For anyone having issues on Gentoo, it’s be great if you could test the current code.

**Comment by stevecheckoway** [comment] 2018-08-31 21:58
Building and installing gems on Gentoo is now tested by our continuous integration. I've also pushed a prerelease for version 2.0.0 to rubygems.org. It'd be great if anyone who was having problems in the past could give it a shot. I'd like to make sure everything is working properly before we release 2.0.0.

**Comment by kaspergrubbe** [comment] 2018-10-10 15:41
@stevecheckoway Current code as in version 2.0.0?

**Comment by stevecheckoway** [comment] 2018-11-12 20:36
I'm closing this because as far as I've tested, this should work correctly now. If it doesn't, please re-open this issue (or file a new one).

**Closed by stevecheckoway** 2018-11-12 20:36 UTC
