### ISSUE TITLE
Fail to build gem

### ISSUE THREAD

**Issue by titibouboul** [rubys/nokogumbo#17] opened 2015-01-06 21:14 UTC
When trying to install nokogumbo on a Ruby 2.0.0 environment (Windows 8 64bit), I have the following error:

$ gem install nokogumbo -v '1.2.0'               
> Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing nokogumbo:
ERROR: Failed to build gem native extension.

>     c:/RailsInstaller/Ruby2.0.0/bin/ruby.exe extconf.rb
> checking for xmlNewDoc() in -lxml2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

> Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=c:/RailsInstaller/Ruby2.0.0/bin/ruby
        --with-xml2lib
        --without-xml2lib
c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:720:in `try_func'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:950:in `block in have_library'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:310:in `open'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:310:in `open'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
        from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/mkmf.rb:945:in `have_library'
        from extconf.rb:4:in `<main>'

> Gem files will remain installed in c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/nokogumbo-1.2.0 for inspection.
Results logged to c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/nokogumbo-1.2.0/ext/nokogumboc/gem_make.out

**Comment by rubys** [comment] 2015-01-06 21:24
Looks like a duplicate of https://github.com/rubys/nokogumbo/issues/9 ?

**Comment by rubys** [comment] 2015-01-14 17:09
Closing as a duplicate

**Closed by rubys** 2015-01-14 17:09 UTC
